jwt:
  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/kyungkidb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root